# .github/workflows/chromatic.yml

# Other configuration required
name: Publish to Chromatic

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/frontend-web/*'
      - 'apps/frontend-web/**'

jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Comment on pull request
        uses: octokit/request-action@v2.x
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          route: POST /repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
          headers: |
            Authorization: token ${{ secrets.ACCESS_TOKEN }}
            Accept: application/vnd.github.v3+json
          body: |
            "The deployed Storybook is available on Chromatic: ${{ steps.chromatic.outputs.storybookUrl }}"
